// SPDX-License-Identifier: AGPL-3.0-only
pragma solidity 0.8.19;

// ==============================================================
//  _____                 _      _____ _                        |
// |  _  |_ _ ___ ___ ___| |_   |   __|_|___ ___ ___ ___ ___    |
// |   __| | | . | . | -_|  _|  |   __| |   | .'|   |  _| -_|   |
// |__|  |___|  _|  _|___|_|    |__|  |_|_|_|__,|_|_|___|___|   |
//           |_| |_|                                            |
// ==============================================================
// ========================= IScoreGauge ========================
// ==============================================================

// Modified fork from Curve Finance: https://github.com/curvefi 
// @title Liquidity Gauge
// @author Curve Finance
// @license MIT
// @notice Used for measuring liquidity and insurance

// Puppet Finance: https://github.com/GMX-Blueberry-Club/puppet-contracts

// Primary Author
// johnnyonline: https://github.com/johnnyonline

// Reviewers
// itburnz: https://github.com/nissoh

// ==============================================================

interface IScoreGauge {

    struct EpochInfo {
        uint256 profitRewards;
        uint256 volumeRewards;
        uint256 totalProfit;
        uint256 totalVolume;
        uint256 profitWeight;
        uint256 volumeWeight;
        mapping(address => bool) claimed;
        mapping(address => UserPerformance) userPerformance;
    }

    struct UserPerformance {
        uint256 volume;
        uint256 profit;
    }

    /// @notice The ```claimableRewards``` returns the amount of rewards claimable by a user for a given epoch
    /// @param _epoch The uint256 value of the epoch
    /// @param _user The address of the user
    /// @return _userReward The uint256 value of the claimable rewards, with 18 decimals
    function claimableRewards(uint256 _epoch, address _user) external view returns (uint256 _userReward);

    /// @notice The ```userPerformance``` function returns the performance of a user for a given epoch
    /// @param _epoch The uint256 value of the epoch
    /// @param _user The address of the user
    /// @return _volume The uint256 value of the volume generated by the user, USD denominated, with 30 decimals
    /// @return _profit The uint256 value of the profit generated by the user, USD denominated, with 30 decimals
    function userPerformance(uint256 _epoch, address _user) external view returns (uint256 _volume, uint256 _profit);

    /// @notice The ```hasClaimed``` function returns whether a user has claimed rewards for a given epoch
    /// @param _epoch The uint256 value of the epoch
    /// @param _user The address of the user
    /// @return _hasClaimed The bool value of whether the user has claimed rewards or not
    function hasClaimed(uint256 _epoch, address _user) external view returns (bool _hasClaimed);

    /// @notice The ```isKilled``` function returns whether the gauge is killed or not
    /// @return _isKilled The bool value of the gauge status
    function isKilled() external view returns (bool _isKilled);

    /// @notice The ```claim``` function allows a user to claim rewards for a given epoch
    /// @param _epoch The uint256 value of the epoch
    /// @param _receiver The address of the receiver of rewards
    /// @return _rewards The uint256 value of the claimable rewards, with 18 decimals
    function claim(uint256 _epoch, address _receiver) external returns (uint256 _rewards);

    /// @notice The ```claimMany``` function allows a user to claim rewards for multiple epochs
    /// @param _epochs The uint256[] value of the epochs
    /// @param _receiver The address of the receiver of rewards
    function claimMany(uint256[] calldata _epochs, address _receiver) external returns (uint256 _rewards);

    /// @notice The ```depositRewards``` function allows the minter to mint rewards for the specified epoch
    /// @param _epoch The uint256 value of the epoch
    /// @param _amount The uint256 value of the amount of minted rewards, with 18 decimals
    function depositRewards(uint256 _epoch, uint256 _amount) external;

    /// @notice The ```updateUserScore``` is called by Routes when a trade is settled, for each user (Trader/Puppet)
    /// @param _volume The uint256 value of the cumulative volume generated, USD denominated, with 30 decimals
    /// @param _profit The uint256 value of the profit, USD denominated, with 30 decimals
    /// @param _user The address of the user
    function updateUserScore(uint256 _volume, uint256 _profit, address _user) external;

    /// @notice The ```killMe``` is called by the admin to kill the gauge
    function killMe() external;

    /// @notice Transfer ownership of GaugeController to `_futureAdmin`
    /// @param _futureAdmin Address to have ownership transferred to
    function commitTransferOwnership(address _futureAdmin) external;

    /// @notice Apply pending ownership transfer
    function applyTransferOwnership() external;

    // ============================================================================================
    // Events
    // ============================================================================================

    event DepositRewards(uint256 amount);
    event Claim(uint256 indexed epoch, uint256 userReward, address indexed user, address indexed receiver);
    event UserScoreUpdate(address indexed user, uint256 volume, uint256 profit);
    event CommitOwnership(address futureAdmin);
    event ApplyOwnership(address admin);

    // ============================================================================================
    // Errors
    // ============================================================================================

    error NotMinter();
    error InvalidEpoch();
    error AlreadyClaimed();
    error NotRoute();
    error NotAdmin();
    error InvalidWeights();
    error NoRewards();
    error ZeroAddress();
}